version: '3'

env:
  NAME: py-utils

dotenv: ['.env']

tasks:
  build:
    cmds:
      - task: amd
        vars:
          VERSION: latest
  amd:
    internal: true
    cmds:
      - | 
        docker buildx build \
          --builder ${AMD64_BUILDER} \
          --platform linux/amd64 \
          --build-arg apt_cacher=${APT_CACHER} \
          --push -t ${REGISTRY}/${NAME}:{{.VERSION}} .
      - ssh ${REMOTE_HOST} "docker pull ${REGISTRY}/${NAME}:{{.VERSION}}"
    silent: true

  arm:
    internal: true
    cmds:
      - | 
        docker buildx build \
          --platform linux/arm64 \
          --build-arg apt_cacher=${APT_CACHER} \
          --push -t ${REGISTRY}/${NAME}:{{.VERSION}} .
    silent: true

  dev:
    desc: Build development Docker image using Dockerfile.dev
    cmds:
      - |
        docker buildx build \
          --platform linux/arm64 \
          --build-arg apt_cacher=${APT_CACHER} \
          -f Dockerfile.dev \
          --push -t ${REGISTRY}/${NAME}:dev .
    silent: true
